# Generated by Django 5.0.3 on 2024-03-22 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajeevi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ajeevi_app.master_table')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('district_zone', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('state_ward', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='entity_type',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ajeevi_app.master_table')),
                ('entity_name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entity_type',
                'managed': False,
            },
        ),
    ]
