# Generated by Django 5.0.3 on 2024-03-22 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajeevi_app', '0002_address_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_table',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'branch_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ajeevi_app.master_table')),
                ('person_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='branch_address',
            fields=[
                ('branch_id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ajeevi_app.branch_table')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_zone', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'branch_address',
                'managed': False,
            },
        ),
    ]
