# Generated by Django 5.0.3 on 2024-03-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajeevi_app', '0003_branch_table_contact_table_branch_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_contact',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'branch_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='contact_table',
        ),
    ]
